/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTampilan;


import java.awt.Color;



/**
 *
 * @author ACER
 */
public class formkaryawan extends javax.swing.JFrame {
    public void ViewData(){
    }

    /**
     * Creates new form formkaryawan
     */
    public formkaryawan() {
        initComponents();
        jPanel2.setBackground(new Color(255,255,255,120));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        txttmptlahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cmbjabatan = new javax.swing.JComboBox<>();
        rdmenikah = new javax.swing.JRadioButton();
        rdmblmmenikah = new javax.swing.JRadioButton();
        cmbagama = new javax.swing.JComboBox<>();
        rdlk = new javax.swing.JRadioButton();
        rdpr = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbkaryawan = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1380, 820));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM KELOLA DATA KARYAWAN ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1420, 100);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("NIK ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 150, 90, 16);
        getContentPane().add(txtnik);
        txtnik.setBounds(350, 150, 220, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 150, 220, 20);
        getContentPane().add(txtnama);
        txtnama.setBounds(350, 180, 220, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 180, 70, 16);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(350, 180, 220, 20);
        getContentPane().add(txttmptlahir);
        txttmptlahir.setBounds(350, 210, 220, 20);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Tempat Lahir");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 210, 90, 16);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(350, 210, 220, 20);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Tanggal Lahir");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 240, 100, 20);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Jabatan ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 270, 90, 16);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Jenis Kelamin");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(700, 150, 100, 30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Agama");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(700, 180, 90, 16);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Status");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(700, 210, 100, 16);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setText("Alamat ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(700, 240, 100, 16);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(350, 240, 220, 20);

        cmbjabatan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direktur Utama", "Direktur Keuangan", "Direktur Personalia", "Manager Personal ", "Manager Pemasar", "Manager Gudang" }));
        getContentPane().add(cmbjabatan);
        cmbjabatan.setBounds(350, 270, 220, 22);

        buttonGroup2.add(rdmenikah);
        rdmenikah.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdmenikah.setSelected(true);
        rdmenikah.setText("Menikah ");
        getContentPane().add(rdmenikah);
        rdmenikah.setBounds(800, 210, 79, 25);

        buttonGroup2.add(rdmblmmenikah);
        rdmblmmenikah.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdmblmmenikah.setText("Belum Menikah ");
        rdmblmmenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdmblmmenikahActionPerformed(evt);
            }
        });
        getContentPane().add(rdmblmmenikah);
        rdmblmmenikah.setBounds(900, 210, 120, 25);

        cmbagama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen ", "Hindu", "Budha" }));
        getContentPane().add(cmbagama);
        cmbagama.setBounds(800, 180, 220, 22);

        buttonGroup1.add(rdlk);
        rdlk.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdlk.setText("Laki-laki");
        rdlk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlkActionPerformed(evt);
            }
        });
        getContentPane().add(rdlk);
        rdlk.setBounds(800, 150, 73, 25);

        buttonGroup1.add(rdpr);
        rdpr.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdpr.setSelected(true);
        rdpr.setText("Perempuan ");
        getContentPane().add(rdpr);
        rdpr.setBounds(900, 150, 120, 25);

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(800, 240, 220, 100);

        tbkaryawan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tbkaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK ", "Nama", "Tempat Lahir", "Tanggal Lahir", "Jabatan ", "Jenis Kelamin", "Agama", "Status", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tbkaryawan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(260, 420, 770, 230);

        btnsimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnsimpan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tutorial/image/save1.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan);
        btnsimpan.setBounds(900, 670, 130, 50);

        btntambah.setBackground(new java.awt.Color(255, 255, 255));
        btntambah.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tutorial/image/tambah1.png"))); // NOI18N
        btntambah.setText("Tambah");
        getContentPane().add(btntambah);
        btntambah.setBounds(260, 670, 120, 50);

        btnupdate.setBackground(new java.awt.Color(255, 255, 255));
        btnupdate.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tutorial/image/edit1.png"))); // NOI18N
        btnupdate.setText("Update");
        getContentPane().add(btnupdate);
        btnupdate.setBounds(410, 670, 130, 50);

        btnhapus.setBackground(new java.awt.Color(255, 255, 255));
        btnhapus.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tutorial/image/hapus2.png"))); // NOI18N
        btnhapus.setText("Hapus\n");
        getContentPane().add(btnhapus);
        btnhapus.setBounds(570, 670, 130, 50);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton5.setText("Cari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(626, Short.MAX_VALUE)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(187, 187, 187))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(330, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 100, 1030, 640);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tutorial/image/background1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 1420, 640);

        setSize(new java.awt.Dimension(1436, 784));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdlkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdlkActionPerformed

    private void rdmblmmenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdmblmmenikahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdmblmmenikahActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formkaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbagama;
    private javax.swing.JComboBox<String> cmbjabatan;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JRadioButton rdlk;
    private javax.swing.JRadioButton rdmblmmenikah;
    private javax.swing.JRadioButton rdmenikah;
    private javax.swing.JRadioButton rdpr;
    private javax.swing.JTable tbkaryawan;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txttmptlahir;
    // End of variables declaration//GEN-END:variables
}
